version: "3"
services:
  backend:
    build: ./back
    container_name: "turismo_back"
    command: sh -c 'npm install; npm start'
    ports:
      - "3003:3003"
    volumes:
      - ./back:/back
    depends_on:
      - "database"

  database:
    container_name: "turismo_db"
    image: redis
    ports:
      - "6379:6379"

  frontend:
    build: ./front
    container_name: "turismo_front"
    command: sh -c 'npm install; npm start'
    ports:
      - "3000:3000"
    volumes:
      - ./front:/front
    depends_on:
      - "backend"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
